<a href="https://colab.research.google.com/github/cupofphotones/Pytorch-in-Google-Colab/blob/master/pytorch_playingwithtensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Видос](https://www.youtube.com/watch?v=yXlZaMPP3YM&list=PLwwk4BHih4fj4DyxylZTHcdYk3L2MC2pa&index=6&t=0s)

In [0]:
!pip install torch

In [0]:
import torch

In [0]:
x = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
y = torch.Tensor([[12,11,10,9],
                [8,7,6,5],
                [4,3,2,1]])

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]), tensor([[12., 11., 10.,  9.],
         [ 8.,  7.,  6.,  5.],
         [ 4.,  3.,  2.,  1.]]))

In [0]:
mask = x>3
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [0]:
y = x
y[0,0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [0]:
x = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [0]:
y = x.clone()
y[0,0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [0]:
x.dtype

torch.float32

In [0]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [0]:
import numpy as np
z = np.array([[1,2,3,4],
              [4,3,2,1]])
z

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [0]:
z.dtype

dtype('int64')

In [0]:
z = torch.from_numpy(z)
z

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [0]:
z.dtype

torch.int64

In [0]:
z = z.numpy()

In [0]:
z.dtype

dtype('int64')